name: "Build and pre-release"

on:
  push:
    branches:
      - main

env:
  PACKAGE_VERSION: 1.0
  PROJECT_PATH: 'src/Mediator/Mediator.csproj'

jobs:
  build:
    name: 'Build and test'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'

      - name: 'Restore packages'
        run: dotnet restore
        working-directory: ./

      - name: 'Build project'
        run: dotnet build -c Release --no-restore
        working-directory: ./
        
      - name: 'Run tests'
        run: dotnet test --no-restore -c Release --no-build --logger:"console;verbosity=normal"
        working-directory: ./
        
  package:
    name: 'Publish package'
    needs: build
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'

      - name: 'Compile version'
        id: compile-version
        run: |
          echo "PACKAGE_VERSION=${{ env.PACKAGE_VERSION }}-alpha.${{github.run_number}}" >> $GITHUB_ENV
          echo ${{ env.PACKAGE_VERSION }}

      - name: Build and Publish Medi8.Net
        uses: drusellers/publish-nuget@master
        with:
          project-file-path: ${{ env.PROJECT_PATH }}
          version: ${{ env.PACKAGE_VERSION }}
          tag-commit: false
          nuget-key: ${{ secrets.NUGET_AUTH_TOKEN }}