name: "Release and publish"

on:
  push:
    tags:
      - 'v*'

env:
  PROJECT_PATH: 'src/Mediator/Mediator.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'

      - name: 'Restore packages'
        run: dotnet restore
        working-directory: ./

      - name: 'Build project'
        run: dotnet build -c Release --no-restore
        working-directory: ./
        
      - name: 'Run tests'
        run: dotnet test --no-restore --c Release --no-build --logger:"console;verbosity=normal"
        working-directory: ./

      # https://github.com/battila7/get-version-action
      - name: 'Get Version'
        id: version
        uses: battila7/get-version-action@v2

      - name: 'Pack project'
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: 'Push package'
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}